/**
 * OCRテキストを試験問題に変換するユーティリティ
 * PDF OCR結果 → 試験問題データ形式へ変換
 */

/**
 * OCR結果から問題を抽出
 * @param {Array} ocrResults - PDF OCR処理結果の配列
 * @returns {Array} 問題オブジェクトの配列
 */
export function extractQuestionsFromOCR(ocrResults) {
  if (!ocrResults || !Array.isArray(ocrResults)) {
    console.error('Invalid OCR results format');
    return [];
  }

  const questions = [];
  let questionId = 1;

  // OCR結果をテキストに統合
  const fullText = ocrResults
    .map(result => result.text || '')
    .join('\n');

  // 問題を抽出（複数の区切り文字に対応）
  const questionPatterns = [
    // パターン1: "問1"、"【1】" 形式
    /(?:問\s*(\d+)|【(\d+)】|(\d+)\s*[.．。])\s*(.+?)(?=(?:問\s*\d+|【\d+】|\d+\s*[.．。]|$))/gs,
    // パターン2: 改行区切り
    /^[^。]*。/gm
  ];

  // テキストから問題候補を分割
  const questionTexts = splitIntoQuestions(fullText);

  questionTexts.forEach((questionText, index) => {
    if (questionText.trim().length < 10) return;  // 短すぎるテキストは除外

    const question = parseQuestionText(questionText, questionId);
    if (question) {
      questions.push(question);
      questionId++;
    }
  });

  return questions;
}

/**
 * テキストを問題単位に分割
 */
function splitIntoQuestions(text) {
  // 改行で区切った後、複数の改行や句点で再分割
  const lines = text.split(/\n+/);
  const questions = [];
  let currentQuestion = '';

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) return;

    if (currentQuestion &&
        (trimmed.match(/^(問|\d+\.|【\d+】|○|×|□)/) ||
         currentQuestion.split('。').length > 2)) {
      questions.push(currentQuestion.trim());
      currentQuestion = trimmed;
    } else {
      currentQuestion += '\n' + trimmed;
    }
  });

  if (currentQuestion.trim()) {
    questions.push(currentQuestion.trim());
  }

  return questions;
}

/**
 * 問題テキストをパースして問題オブジェクトに変換
 */
function parseQuestionText(text, questionId) {
  // テキストから不要な部分を削除
  let cleanText = text
    .replace(/ページ\s*\d+/g, '')  // "ページ XX" を削除
    .replace(/^[\d.【】()（）]*/, '')  // 先頭の番号を削除
    .trim();

  if (cleanText.length < 15) return null;

  // 問題文と選択肢を分割
  const parts = cleanText.split(/[\n。]+/).filter(p => p.trim());
  if (parts.length < 2) {
    // 選択肢がない場合は問題文のみ
    return {
      id: questionId,
      category: categorizeQuestion(cleanText),
      text: cleanText,
      options: generateDefaultOptions(),
      isAutoGenerated: true
    };
  }

  const questionText = parts[0];
  const optionsText = parts.slice(1);

  // 選択肢を抽出
  const options = extractOptions(optionsText, questionText);

  return {
    id: questionId,
    category: categorizeQuestion(questionText),
    text: questionText.substring(0, 300),  // 最大300文字
    options: options.length > 0 ? options : generateDefaultOptions(),
    isAutoGenerated: true
  };
}

/**
 * 問題をカテゴリーに分類
 */
function categorizeQuestion(text) {
  const categories = {
    '法律知識': ['風俗営業法', '法律', '法令', '法定', 'законо', '規定'],
    '営業管理': ['営業', '店舗', 'ホール', '申請', '許可', '業務', '管理'],
    '機械知識': ['機械', '遊技機', 'パチンコ', '設置', 'メダル', '認定']
  };

  for (const [category, keywords] of Object.entries(categories)) {
    if (keywords.some(keyword => text.includes(keyword))) {
      return category;
    }
  }

  return 'その他';
}

/**
 * 選択肢を抽出
 */
function extractOptions(optionsText, questionText) {
  const options = [];
  const optionMarkers = ['ア', 'イ', 'ウ', 'エ', 'a', 'b', 'c', 'd', '①', '②', '③', '④'];

  optionsText.forEach((optText, index) => {
    const cleanOption = optText
      .replace(/^[ア-エabcd①-④]\s*[.。]?\s*/, '')  // 先頭のマーカーを削除
      .trim()
      .substring(0, 200);  // 最大200文字

    if (cleanOption.length > 5) {
      options.push({
        id: optionMarkers[index] || `${index}`,
        text: cleanOption,
        isCorrect: false  // デフォルトは不正解（手動修正が必要）
      });
    }
  });

  return options;
}

/**
 * デフォルトの選択肢を生成
 */
function generateDefaultOptions() {
  return [
    { id: 'a', text: '正しい選択肢', isCorrect: true },
    { id: 'b', text: '間違い選択肢', isCorrect: false },
    { id: 'c', text: '間違い選択肢', isCorrect: false },
    { id: 'd', text: '間違い選択肢', isCorrect: false }
  ];
}

/**
 * OCR結果を問題データベース形式にシリアライズ
 */
export function ocrResultsToDatabase(ocrResults) {
  const questions = extractQuestionsFromOCR(ocrResults);

  return {
    version: '1.0',
    timestamp: new Date().toISOString(),
    source: 'PDF OCR',
    total_questions: questions.length,
    categories: {
      '法律知識': questions.filter(q => q.category === '法律知識').length,
      '営業管理': questions.filter(q => q.category === '営業管理').length,
      '機械知識': questions.filter(q => q.category === '機械知識').length,
      'その他': questions.filter(q => q.category === 'その他').length
    },
    questions: questions
  };
}

/**
 * サンプル問題データを生成（フォールバック用）
 */
export function generateSampleQuestions() {
  return [
    {
      id: 1,
      category: '法律知識',
      text: '風俗営業法について、以下の選択肢のうち正しいものはどれですか？',
      options: [
        { id: 'a', text: '正しい選択肢', isCorrect: true },
        { id: 'b', text: '間違い選択肢', isCorrect: false },
        { id: 'c', text: '間違い選択肢', isCorrect: false },
        { id: 'd', text: '間違い選択肢', isCorrect: false }
      ]
    },
    {
      id: 2,
      category: '営業管理',
      text: 'パチンコ店舗の営業許可申請に必要な書類は？',
      options: [
        { id: 'a', text: '間違い選択肢', isCorrect: false },
        { id: 'b', text: '正しい選択肢', isCorrect: true },
        { id: 'c', text: '間違い選択肢', isCorrect: false },
        { id: 'd', text: '間違い選択肢', isCorrect: false }
      ]
    },
    {
      id: 3,
      category: '機械知識',
      text: 'パチンコ機械の認定基準について正しいものは？',
      options: [
        { id: 'a', text: '正しい選択肢', isCorrect: true },
        { id: 'b', text: '間違い選択肢', isCorrect: false },
        { id: 'c', text: '間違い選択肢', isCorrect: false },
        { id: 'd', text: '間違い選択肢', isCorrect: false }
      ]
    }
  ];
}
